

trigger:
- main

pool: default

jobs:
- job: infraJOB
  steps:
   - task: TerraformInstaller@1
     inputs:
       terraformVersion: 'latest'
   - script: |
       cd Environment\Dev
       terraform init
       terraform fmt
       terraform validate
       terraform plan
       terraform apply --auto-approve
   - task: AzureCLI@0
     inputs:
       connectedServiceNameSelector: 'connectedServiceNameARM'
       connectedServiceNameARM: 'alok-service-con'
       scriptLocation: 'inlineScript'
       inlineScript: |
         az group create --name alok1-rg --location eastus
         az acr create --resource-group alok1-rg --name alok1acr --sku Basic
         az acr show --name alok1acr --resource-group alok1-rg
         az acr login -n alok1acr --expose-token
       cwd: '$(System.DefaultWorkingDirectory)'

   
