apiVersion: apps/v1
kind: Deployment
metadata:
  name: alok-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: alokacr.azurecr.io/my-first-image:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: alok-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
